version: '3'
services:
  graphite:
    build: ./graphite/
    ports:
     - "7080:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"
  grafana:
    build: ./grafana/
    ports:
     - "3000:3000"
    links:
     - graphite:graphite
